<a href="https://colab.research.google.com/github/RakelOuakil/demo-repo/blob/main/exercice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction

In [1]:
import numpy as np

# Données des tâches (M1, M2, M3) - Chaque colonne représente une tâche
taches = np.array([
    [6, 3, 10, 14, 5, 9, 7, 11, 2, 3],  # Temps sur M1
    [1, 5, 4, 6, 10, 6, 9, 8, 6, 1],   # Temps sur M2
    [5, 8, 1, 3, 6, 10, 12, 9, 6, 7]   # Temps sur M3
])

nb_taches = taches.shape[1]  # Nombre de tâches

In [2]:
def calculer_cmax(sequence):
    temps = np.zeros((3, len(sequence)))
    temps[0, 0] = taches[0, sequence[0]]
    temps[1, 0] = temps[0, 0] + taches[1, sequence[0]]
    temps[2, 0] = temps[1, 0] + taches[2, sequence[0]]

    for i in range(1, len(sequence)):
        temps[0, i] = temps[0, i-1] + taches[0, sequence[i]]
        temps[1, i] = max(temps[0, i], temps[1, i-1]) + taches[1, sequence[i]]
        temps[2, i] = max(temps[1, i], temps[2, i-1]) + taches[2, sequence[i]]

    return temps[2, -1]

In [3]:
sequence = list(range(nb_taches))

# Methode De Liste

### Règle de priorité : SPT (Shortest Processing Time)

In [4]:
def methode_liste(l):
    U= []
    t=0
    taches_restantes = list(range(nb_taches))
    while taches_restantes:
        taches_dispo = [j for j in taches_restantes if taches[0][j] > 0]
        if taches_dispo :
            i = min(taches_dispo, key=lambda j: taches[0][j])
            U.append(i)
            taches_restantes.remove(i)
        else :
            t = min([taches[0][j] for j in taches_restantes])
    return U


# Exécution de l'algorithme
ordre_taches = methode_liste(taches)
cmax_spt = calculer_cmax(ordre_taches)

# Affichage des résultats
print("Ordre des tâches selon SPT :", ordre_taches)
print("Cmax pour cet ordre :", cmax_spt)

Ordre des tâches selon SPT : [8, 1, 9, 4, 0, 6, 5, 2, 7, 3]
Cmax pour cet ordre : 79.0


# Méthode de Johnson avec machine virtuelle MV = M1 + M2

In [5]:
def methode_johnson_mv():
    mv = taches[0] + taches[1]  # Machine Virtuelle MV = M1 + M2
    m3 = taches[2]

    indices = list(range(nb_taches))
    debut, fin = [], []

    for i in indices:
        if mv[i] <= m3[i]:
            debut.append(i)
        else:
            fin.append(i)
    debut.sort(key=lambda j: mv[j])
    fin.sort(key=lambda j: m3[j], reverse=True)

    return debut + fin




ordre_johnson = methode_johnson_mv()
cmax_johnson = calculer_cmax(ordre_johnson)


print("Ordre des tâches selon Johnson :", ordre_johnson)
print("Cmax pour cet ordre :", cmax_johnson)

Ordre des tâches selon Johnson : [9, 1, 6, 5, 7, 4, 8, 0, 3, 2]
Cmax pour cet ordre : 75.0


# Méthode de voisinage

In [6]:
def recherche_voisinage(seq):
    meilleure_seq, meilleur_cmax = seq[:], calculer_cmax(seq)
    for i in range(len(seq) - 1):
        voisin = seq[:]
        voisin[i], voisin[i+1] = voisin[i+1], voisin[i]
        cmax_voisin = calculer_cmax(voisin)
        if cmax_voisin < meilleur_cmax:
            meilleure_seq, meilleur_cmax = voisin, cmax_voisin

    return meilleure_seq, meilleur_cmax

# Exemple d'utilisation avec la séquence générée par une méthode comme Johnson
sequence_initiale = [9, 1, 6, 5, 7, 4, 8, 0, 3, 2]
meilleure_sequence, cmax_optimal = recherche_voisinage(sequence_initiale)


print(f"Meilleure séquence pour la méthode de voisinage : {meilleure_sequence}, Cmax : {cmax_optimal}")

Meilleure séquence pour la méthode de voisinage : [9, 1, 6, 5, 7, 4, 8, 0, 3, 2], Cmax : 75.0


# Conclusion

SPT (Shortest Processing Time) : L'ordre des tâches est [8, 1, 9, 4, 0, 6, 5, 2, 7, 3], avec un Cmax de 79.0. Cette méthode privilégie les tâches courtes en premier, mais donne un Cmax plus élevé.

Johnson (avec machine virtuelle M1 + M2) : L'ordre des tâches est [9, 1, 6, 5, 7, 4, 8, 0, 3, 2], avec un Cmax de 75.0. Cette méthode optimise mieux le Cmax en prenant en compte toutes les machines.

Méthode de voisinage : La séquence obtenue est la même que celle de Johnson, avec un Cmax de 75.0. Cela montre que la méthode de voisinage n'a pas amélioré la solution de Johnson.

Conclusion : La méthode Johnson est la plus efficace pour minimiser le Cmax.